Imports Microsoft.VisualBasic
Imports System
Imports System.Web.UI
Imports DevExpress.Web
Imports System.Diagnostics
Imports WsSeguridad
Imports Modulos.WB.Clases
Imports System.Data
Imports System.IO
Imports System.IO.StreamWriter
Imports System.Threading
Imports System.Globalization
Imports ComponentArt.Web.UI

Partial Class Cobranza_WfSimulacionDeAbonoACapital
    Inherits System.Web.UI.Page
    Private Servicio As New WsFuncionalidad.Funcionalidad


    Protected Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs)
        If IsPostBack Then
            'ConfiguraGrids()

        Else
            'ConfiguraGrids()

        End If

        LlenaTablaReduccionDePlazoActual()
        LlenaTablaReduccionDePlazoPropuesta()
        LlenaTablaRequerimiento()
        LlenaTablaRequerimiento2()

        Dim Texto As New Literal()
        Dim Cadena As String = ""
        Cadena += ("<table border=""0"" style=""width:100%"">")
        Cadena += ("    <tr>")
        Cadena += ("        <td>")
        Cadena += ("            <table border=""1"" cellpadding=""1"" cellspacing=""1"" width=""100%"">")
        Cadena += ("                <tr>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        No.")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha Inicial<BR/>Periodo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha Final<BR/>Periodo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha de<BR/>Exigibilidad")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Base de Cálculo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Intereses")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Amortización")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Saldo Insoluto")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Pago")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Pago con IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Seguro Bien")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Seguro IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Otros Cargos")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Total")
        Cadena += ("                    </td>")
        Cadena += ("                </tr>")

        'Aqui comienza a recorrer el Dataset, para dibujar la tabla con los datos
        Cadena += ("                <tr>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                </tr>")
        'Aqui termina a recorrer el Dataset, para dibujar la tabla con los datos

        Cadena += ("            </table>")
        Cadena += ("        </td>")
        Cadena += ("    </tr>")
        Cadena += ("</table>")

        Texto.Text = Cadena

        PlaceHolder1.Controls.Add(Texto)

    End Sub


    Private Sub LlenaTablaReduccionDePlazoActual()
        Dim Texto As New Literal()
        Dim Cadena As String = ""
        Cadena += ("<table border=""0"" style=""width:100%"">")
        Cadena += ("    <tr>")
        Cadena += ("        <td>")
        Cadena += ("            <table border=""1"" cellpadding=""1"" cellspacing=""1"" width=""100%"">")
        Cadena += ("                <tr>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        No.")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha Inicial<BR/>Periodo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha Final<BR/>Periodo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha de<BR/>Exigibilidad")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Base de Cálculo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Intereses")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Amortización")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Saldo Insoluto")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Pago")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Pago con IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Seguro Bien")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Seguro IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Otros Cargos")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Total")
        Cadena += ("                    </td>")
        Cadena += ("                </tr>")

        'Aqui comienza a recorrer el Dataset, para dibujar la tabla con los datos
        Cadena += ("                <tr>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                </tr>")
        'Aqui termina a recorrer el Dataset, para dibujar la tabla con los datos

        Cadena += ("            </table>")
        Cadena += ("        </td>")
        Cadena += ("    </tr>")
        Cadena += ("</table>")

        Texto.Text = Cadena

        PlaceHolderActual.Controls.Add(Texto)

    End Sub



    Private Sub LlenaTablaReduccionDePlazoPropuesta()
        Dim Texto As New Literal()
        Dim Cadena As String = ""
        Cadena += ("<table border=""0"" style=""width:100%"">")
        Cadena += ("    <tr>")
        Cadena += ("        <td>")
        Cadena += ("            <table border=""1"" cellpadding=""1"" cellspacing=""1"" width=""100%"">")
        Cadena += ("                <tr>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        No.")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha Inicial<BR/>Periodo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha Final<BR/>Periodo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha de<BR/>Exigibilidad")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Base de Cálculo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Intereses")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Amortización")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Saldo Insoluto")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Pago")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Pago con IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Seguro Bien")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Seguro IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Otros Cargos")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Total")
        Cadena += ("                    </td>")
        Cadena += ("                </tr>")

        'Aqui comienza a recorrer el Dataset, para dibujar la tabla con los datos
        Cadena += ("                <tr>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                </tr>")
        'Aqui termina a recorrer el Dataset, para dibujar la tabla con los datos

        Cadena += ("            </table>")
        Cadena += ("        </td>")
        Cadena += ("    </tr>")
        Cadena += ("</table>")

        Texto.Text = Cadena

        PlaceHolderPropuesta.Controls.Add(Texto)
    End Sub



    Private Sub LlenaTablaRequerimiento()
        Dim Texto As New Literal()
        Dim Cadena As String = ""
        Cadena += ("<table border=""0"" style=""width:100%"">")
        Cadena += ("    <tr>")
        Cadena += ("        <td>")
        Cadena += ("            <table border=""1"" cellpadding=""1"" cellspacing=""1"" width=""100%"">")
        Cadena += ("                <tr>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        No.")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha Inicial<BR/>Periodo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha Final<BR/>Periodo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha de<BR/>Exigibilidad")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Base de Cálculo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Intereses")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Amortización")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Saldo Insoluto")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Pago")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Pago con IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Seguro Bien")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Seguro IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Otros Cargos")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Total")
        Cadena += ("                    </td>")
        Cadena += ("                </tr>")

        'Aqui comienza a recorrer el Dataset, para dibujar la tabla con los datos
        Cadena += ("                <tr>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                </tr>")
        'Aqui termina a recorrer el Dataset, para dibujar la tabla con los datos

        Cadena += ("            </table>")
        Cadena += ("        </td>")
        Cadena += ("    </tr>")
        Cadena += ("</table>")

        Texto.Text = Cadena

        PlaceHolderRequerimiento.Controls.Add(Texto)

    End Sub



    Private Sub LlenaTablaRequerimiento2()
        Dim Texto As New Literal()
        Dim Cadena As String = ""
        Cadena += ("<table border=""0"" style=""width:100%"">")
        Cadena += ("    <tr>")
        Cadena += ("        <td>")
        Cadena += ("            <table border=""1"" cellpadding=""1"" cellspacing=""1"" width=""100%"">")
        Cadena += ("                <tr>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        No.")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha Inicial<BR/>Periodo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha Final<BR/>Periodo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Fecha de<BR/>Exigibilidad")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Base de Cálculo")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Intereses")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Amortización")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Saldo Insoluto")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Pago")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Pago con IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Seguro Bien")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Seguro IVA")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Otros Cargos")
        Cadena += ("                    </td>")
        Cadena += ("                    <td style=""text-align:center; background-color:#D8D8D8"">")
        Cadena += ("                        Total")
        Cadena += ("                    </td>")
        Cadena += ("                </tr>")

        'Aqui comienza a recorrer el Dataset, para dibujar la tabla con los datos
        Cadena += ("                <tr>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                    <td class=""dxrpHeader_Office2010Blue dx-borderBox"" style=""text-align:center"">")
        Cadena += ("                        &nbsp;")
        Cadena += ("                    </td>")
        Cadena += ("                </tr>")
        'Aqui termina a recorrer el Dataset, para dibujar la tabla con los datos

        Cadena += ("            </table>")
        Cadena += ("        </td>")
        Cadena += ("    </tr>")
        Cadena += ("</table>")

        Texto.Text = Cadena

        PlaceHolderRequerimiento2.Controls.Add(Texto)

    End Sub



    Private Sub CallBackTablaSimulacion_Callback(sender As Object, e As ComponentArt.Web.UI.CallBackEventArgs) Handles CallBackTablaSimulacion.Callback
        Dim vMontoDelPrestamo, vTasaAnualSinIVA, vPlazoEnMeses, vPagoConstante, Period, P, I As Double
        Dim PayType As DueDate
        Dim Cadena As String = ""
        Dim SaldoDinamico As Double = 0
        Dim vTasaOriginalAnualSinIVA As Double = 0
        Dim Funcionalidad As String
        Dim Factor As Integer = 0
        Dim TipoPago As String
        Dim Texto As New Literal()

        Cadena += ("<table border=""1"" cellpadding=""0"" cellspacing=""0"" width=""100%"">")
        Cadena += ("     <tr>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"" colspan=""15"">")
        Cadena += ("             La tabla de amortizaci&oacute;n se calcul&oacute; considerando periodos de 30 d&iacute;as")
        Cadena += ("         </td>")
        Cadena += ("     </tr>")
        Cadena += ("     <tr style=""background-color:#00BFFF"">")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>No</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>F. Inicial<br/>Periodo</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>F. Final<br/>periodo</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>Fecha de<br/>exigibilidad</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>Base<br/>Cálculo</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>Intereses</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>Amortización</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>Saldo<br/>Insoluto</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>Pago</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>IVA</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>Pago<br/>con IVA</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>Seguro<br/>Bien</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>Seguro<br/>Vida</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>Otros<br/>Cargos</b>")
        Cadena += ("         </td>")
        Cadena += ("         <td align=""center"" style=""font-family:Arial"">")
        Cadena += ("             <b>Total</b>")
        Cadena += ("         </td>")
        Cadena += ("     </tr>")

        Dim Fmt As String = "###,###,##0.00"
        Dim Fval As Double = 0
        vMontoDelPrestamo = 275875 'Replace(e.Parameters(0), ",", "")
        vTasaAnualSinIVA = 12.95 'e.Parameters(1)
        vTasaOriginalAnualSinIVA = (12.95 / 100) '(e.Parameters(1) / 100)
        vTasaAnualSinIVA = vTasaAnualSinIVA * 1.16 'Se calcula la tasa con IVA
        SaldoDinamico = 275875 'e.Parameters(0)
        If vTasaAnualSinIVA > 1 Then vTasaAnualSinIVA = vTasaAnualSinIVA / 100
        vPlazoEnMeses = 60 'e.Parameters(2)
        TipoPago = "Quincenal" 'e.Parameters(3)
        Funcionalidad = "GeneraTabla" 'e.Parameters(4)


        PayType = DueDate.EndOfPeriod
        vPagoConstante = Math.Abs(-Pmt(vTasaAnualSinIVA / 12, vPlazoEnMeses, vMontoDelPrestamo, Fval, PayType))

        For Period = 1 To vPlazoEnMeses
            P = PPmt(vTasaAnualSinIVA / 12, Period, vPlazoEnMeses, -vMontoDelPrestamo, Fval, PayType)
            P = (Int((P + 0.005) * 100) / 100)
            I = vPagoConstante - P
            I = (Int((I + 0.005) * 100) / 100)

            'TASAS DE INTERES (INICIA)
            Cadena += (" <tr>")
            Cadena += ("    <td align=""center"" style=""font-family:Arial"">")
            Cadena += ("" & Period & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""center"" style=""font-family:Arial"">")
            Cadena += ("" & "&nbsp;" & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""center"" style=""font-family:Arial"">")
            Cadena += ("" & "&nbsp;" & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""center"" style=""font-family:Arial"">")
            Cadena += ("" & "&nbsp;" & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""right"" style=""font-family:Arial"">")
            Cadena += ("" & Format(SaldoDinamico, Fmt) & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""right"" style=""font-family:Arial"">")
            Cadena += ("" & Format(SaldoDinamico * (vTasaOriginalAnualSinIVA / 12), Fmt) & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""right"" style=""font-family:Arial"">")
            Cadena += ("" & Format(P, Fmt) & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""right"" style=""font-family:Arial"">")
            Cadena += ("" & Format(SaldoDinamico - P, Fmt) & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""right"" style=""font-family:Arial"">")
            Cadena += ("" & Format(((SaldoDinamico * (vTasaOriginalAnualSinIVA / 12)) + P), Fmt) & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""right"" style=""font-family:Arial"">")
            Cadena += ("" & Format(((SaldoDinamico * (vTasaOriginalAnualSinIVA / 12)) * 0.16), Fmt) & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""right"" style=""font-family:Arial"">")
            Cadena += ("" & Format(((SaldoDinamico * (vTasaOriginalAnualSinIVA / 12)) + P) + ((SaldoDinamico * (vTasaOriginalAnualSinIVA / 12)) * 0.16), Fmt) & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""center"" style=""font-family:Arial"">")
            Cadena += ("" & "&nbsp;" & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""center"" style=""font-family:Arial"">")
            Cadena += ("" & "&nbsp;" & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""center"" style=""font-family:Arial"">")
            Cadena += ("" & "&nbsp;" & "")
            Cadena += ("    </td>")
            Cadena += ("    <td align=""right"" style=""font-family:Arial"">")
            Cadena += ("" & Format(vPagoConstante, Fmt) & "")
            Cadena += ("    </td>")
            Cadena += ("</tr>")
            'TASAS DE INTERES (TERMINA)

            SaldoDinamico = (SaldoDinamico - P)

        Next Period
        Cadena += ("     </tr>")
        Texto.Text = Cadena



        Me.PlaceHolderSimulacion.Controls.Add(Texto)
        Me.PlaceHolderSimulacion.RenderControl(e.Output)
    End Sub



End Class
